Supernova small UI fix til
sapcc/juno pull request #513
Opened 2024-01-23 15:20 UTC by TilmanHaupt

fixes: [#487](https://github.com/sapcc/juno/issues/487)

New alphabetical sorting in the select and new error messages for supernova.

![Bildschirmfoto 2024-01-23 um 16 16 54](https://github.com/sapcc/juno/assets/147151040/ae4ca35e-fc45-4aa8-96db-22c86237d399)
![Bildschirmfoto 2024-01-23 um 16 18 20](https://github.com/sapcc/juno/assets/147151040/011fa715-c887-41f4-ac4a-2e3a97275b9b)
![Bildschirmfoto 2024-01-23 um 16 18 38](https://github.com/sapcc/juno/assets/147151040/4a33bff3-4216-4bf4-a66b-3a2f69a48df9)

2024-01-25 09:17 UTC, edda requested changes

2024-01-25 09:17 UTC, edda commented on apps/supernova/src/components/filters/FilterSelect.jsx
> +            [].slice
Why not just do `filterLabels?.sort().map((filter)) => ...` ?
What advantage does the `[].slice.call(filterLabels)` give?

2024-01-25 13:34 UTC, ArtieReus requested changes

2024-01-25 13:34 UTC, ArtieReus commented on apps/supernova/package.json
> +  "version": "0.9.7",
Did you also run the `npm install -w supernova` to update the lock file?

2024-01-29 15:28 UTC, ArtieReus approved these changes
lgtm

2024-01-29 15:29 UTC, ArtieReus requested changes

2024-01-29 15:29 UTC, ArtieReus commented on apps/supernova/src/AppContent.jsx
> +        text: "Sorry, there was an issue fetching the data. Possible causes could include network issues, incorrect URL, or server outages. ",
Would you add the message `"Sorry, there was an issue fetching the data. Possible causes could include network issues, incorrect URL, or server outages.` to the parseError method so it is not duplicated in the code?

2024-01-31 10:44 UTC, ArtieReus approved these changes
lgtm

2024-01-31 10:45 UTC, merged