[Supernova] Silence Scheduler for Supernova
sapcc/juno pull request #579
Opened 2024-04-16 11:18 UTC by TilmanHaupt

Add a form to schedule silences for e.g. maintenance. 

fixes #398

2024-04-16 13:45 UTC, ArtieReus requested changes

2024-04-16 13:45 UTC, ArtieReus commented on apps/exampleapp/src/components/AppContent.js
> +                console.log(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>end", e)
Please remove comments

2024-04-16 13:45 UTC, ArtieReus commented on apps/exampleapp/src/components/AppContent.js
> +                console.log(testState)
same same

2024-04-16 13:45 UTC, ArtieReus commented on apps/supernova/src/AppContent.jsx
> +  const { addMessage, resetMessages } = useActions()
do you really use resetMessages?

2024-04-16 13:45 UTC, ArtieReus commented on apps/supernova/src/components/silences/SilenceScheduled.jsx
> +  const date = new Date()
try you memorize the default data. Each rendering would then create a new date.

2024-04-16 13:45 UTC, ArtieReus commented on apps/supernova/src/components/silences/silenceScheduledHelpers.js
> +  console.log(formState.date.start)
same same

2024-04-16 14:17 UTC, ArtieReus commented
When opening the Template form without selecting any template you can still press save and an error will be displayed. I will propose to disable the save button until the template is selected. What do you think?

2024-04-16 14:19 UTC, ArtieReus commented
If the template have same title the select displays the two templates selected. This is probably because the key is the title. I would recomend to create unique ids (index) to avoid it.

2024-04-16 14:21 UTC, ArtieReus commented
Check how the key status is used in the old Supernova. Ex: 
```
"status": "active",
```

2024-04-16 14:27 UTC, ArtieReus commented
Validate template input. Changing for example `editable_labels ` as string crashes the component.

2024-04-16 15:18 UTC, edda requested changes

2024-04-16 15:18 UTC, edda commented on apps/supernova/src/components/silences/silenceScheduledHelpers.js
> +  console.log(b.date.start)
console.log remove plx

2024-04-16 15:18 UTC, edda commented on apps/supernova/src/components/silences/silenceScheduledHelpers.js
> +  console.log(formState.date.start)
and again :)

2024-04-16 15:18 UTC, edda commented on apps/supernova/src/components/silences/silenceScheduledHelpers.js
> +  console.log(formState.date.start)
one more

2024-04-16 15:22 UTC, TilmanHaupt commented on apps/exampleapp/src/components/AppContent.js
> +                console.log(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>end", e)
komplettes file ist rm

2024-04-19 13:46 UTC, ArtieReus approved these changes
Good Job!! lgtm!

2024-04-19 13:48 UTC, merged